data_dir: /home/yuuki/Desktop/competitions/atmaCup/yukiCup-2023-Autumn-atmaCup/data/yukiCup 2023 Autumn x atmaCup
processed_dir: /home/yuuki/Desktop/competitions/atmaCup/yukiCup-2023-Autumn-atmaCup/processed_data
output_dir: /home/yuuki/Desktop/competitions/atmaCup/yukiCup-2023-Autumn-atmaCup/output