hydra:
  job:
    name: train
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/single
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - dir: local

seed: 42
fold: 0

exp_name: exp001
model: cl-tohoku/bert-base-japanese-v3
max_len: 256

# trainer
lr: 0.00002
batch_size: 128
epochs: 10
weight_decay: 0.01
adv_start_epoch: 100
adv_epsilon: 1.0